---

- name: Save file from router
  hosts: 192.168.88.1
  gather_facts: false

  tasks:
       
    - name: backup-file create
      routeros_command:
        commands: /system backup save name=backup_awx
